import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const electron = require('./index.cjs');

export const app = electron.app;
export const BaseWindow = electron.BaseWindow;
export const BrowserWindow = electron.BrowserWindow;
export const BrowserView = electron.BrowserView;
export const WebContentsView = electron.WebContentsView;
export const View = electron.View;
export const ImageView = electron.ImageView;
export const Menu = electron.Menu;
export const MenuItem = electron.MenuItem;
export const Tray = electron.Tray;
export const Notification = electron.Notification;
export const TouchBar = electron.TouchBar;
export const MessageChannelMain = electron.MessageChannelMain;
export const MessagePortMain = electron.MessagePortMain;
export const ipcMain = electron.ipcMain;
export const ipcRenderer = electron.ipcRenderer;
export const contextBridge = electron.contextBridge;
export const webFrame = electron.webFrame;
export const dialog = electron.dialog;
export const shell = electron.shell;
export const clipboard = electron.clipboard;
export const nativeTheme = electron.nativeTheme;
export const nativeImage = electron.nativeImage;
export const session = electron.session;
export const protocol = electron.protocol;
export const net = electron.net;
export const screen = electron.screen;
export const webContents = electron.webContents;
export const globalShortcut = electron.globalShortcut;
export const powerSaveBlocker = electron.powerSaveBlocker;
export const powerMonitor = electron.powerMonitor;
export const systemPreferences = electron.systemPreferences;
export const safeStorage = electron.safeStorage;
export const desktopCapturer = electron.desktopCapturer;
export const crashReporter = electron.crashReporter;
export const autoUpdater = electron.autoUpdater;
export const contentTracing = electron.contentTracing;
export const netLog = electron.netLog;
export const utilityProcess = electron.utilityProcess;
export const pushNotifications = electron.pushNotifications;
export const inAppPurchase = electron.inAppPurchase;
export const parentPort = electron.parentPort;

export default electron;
